---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qi.zhang.
--- DateTime: 2020/4/28 13:48
---

require("ModulesAndPackages.module")
print(module.constant)

module.func3()

module.func1()