---
---数组，就是相同数据类型的元素按一定顺序排列的集合，可以是一维数组和多维数组。
---Lua 数组的索引键值可以使用整数表示，数组的大小不是固定的。
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qi.zhang.
--- DateTime: 2020/4/27 20:31
---

array = {1, 2, "33", {4, 5, 6}}
for i = 1, 4 do
    if type(array[i])=="table" then
        print("array")
    end
    print(array[i])
end