---
---Lua 编程语言流程控制语句通过程序设定一个或多个条件语句来设定。
---在条件为 true 时执行指定程序代码，在条件为 false 时执行其他指定代码。
---以下是典型的流程控制流程图
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seldom.
--- DateTime: 2020/4/26 23:08
---

---
---控制结构的条件表达式结果可以是任何值，Lua认为false和nil为假，true和非nil为真。
---要注意的是Lua中 0 为 true：
---
if 0 then
    print("0 is true")
end

---if ... else
--[[
if(布尔表达式)
then
   --[ 布尔表达式为 true 时执行该语句块 --]
else
   --[ 布尔表达式为 false 时执行该语句块 --]
end
--]]
if 10 > 20 then
    print("10 > 20")
else
    print("10 < 20")
end


---if ... elseif ... else
--[[
if( 布尔表达式 1)
then
--[ 在布尔表达式 1 为 true 时执行该语句块 --]

elseif( 布尔表达式 2)
then
--[ 在布尔表达式 2 为 true 时执行该语句块 --]

elseif( 布尔表达式 3)
then
--[ 在布尔表达式 3 为 true 时执行该语句块 --]
else
--[ 如果以上布尔表达式都不为 true 则执行该语句块 --]
end
--]]
if 10 > 20 then
    print("10 > 20")
elseif 10 > 15 then
    print("10 > 15")
else
    print("10 < 15 < 20")
end