---
---字符串或串(String)是由数字、字母、下划线组成的一串字符。
---Lua 语言中字符串可以使用以下三种方式来表示：
---单引号间的一串字符。
---双引号间的一串字符。
---[[和]]间的一串字符。
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qi.zhang.
--- DateTime: 2020/4/27 12:39
---

---双引号间的一串字符
string1 = "lua"
print("\"字符串 1 是\"", string1)

---单引号间的一串字符
string2 = 'runoob.com'
print("字符串 2 是",string2)
---[[和]]间的一串字符。
string3 = [["Lua 教程"]]
print("字符串 3 是",string3)


---string.format()
string1 = "Lua"
string2 = "Tutorial"
number1 = 10
number2 = 20
-- 基本字符串格式化
print(string.format("基本格式化 %s %s",string1,string2))
-- 日期格式化
date = 2; month = 1; year = 2014
print(string.format("日期格式化 %02d/%02d/%03d", date, month, year))
-- 十进制格式化
print(string.format("%.4f",1/3))
string.format("%c", 83)                 -- 输出S
string.format("%+d", 17.0)              -- 输出+17
string.format("%05d", 17)               -- 输出00017
string.format("%o", 17)                 -- 输出21
string.format("%u", 3.14)               -- 输出3
string.format("%x", 13)                 -- 输出d
string.format("%X", 13)                 -- 输出D
string.format("%e", 1000)               -- 输出1.000000e+03
string.format("%E", 1000)               -- 输出1.000000E+03
string.format("%6.3f", 13)              -- 输出13.000
string.format("%q", "One\nTwo")         -- 输出"One\
-- 　　Two"
string.format("%s", "monkey")           -- 输出monkey
string.format("%10s", "monkey")         -- 输出    monkey
string.format("%5.3s", "monkey")        -- 输出  mon


---字符与整数相互转换
---转换第一个字符
print(string.byte("Lua"))
---转换第三个字符
print(string.byte("Lua", 3))
---转换第一个字符到第三个字符
print(string.byte("Lua", 1, 3))


---其他函数
string1 = "www."
string2 = "runoob"
string3 = ".com"
-- 使用 .. 进行字符串连接
print("连接字符串",string1..string2..string3)

-- 字符串长度
print("字符串长度 ",string.len(string2))

-- 字符串复制 2 次
repeatedString = string.rep(string2,2)
print(repeatedString)


---匹配模式
---Lua 中的匹配模式直接用常规的字符串来描述。
---它用于模式匹配函数 string.find, string.gmatch, string.gsub, string.match。
---你还可以在模式串中使用字符类。
---字符类指可以匹配一个特定字符集合内任何字符的模式项。
---比如，字符类 %d 匹配任意数字。所以你可以使用模式串 %d%d/%d%d/%d%d%d%d 搜索 dd/mm/yyyy 格式的日期：
---
s = "Deadline is 30/05/1999,firm"
date = "%d%d/%d%d/%d%d%d%d"
print(string.sub(s, string.find(s, date)))