---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seldom.
--- DateTime: 2020/5/1 23:06
---

luasql = require "luasql.mysql"
print("===")
--创建环境对象
env = luasql.mysql()
print("===")

-- 连接数据库
conn = env:connect("test","seldom","123456","127.0.0.1",3306)

-- 设置数据库的编码格式
conn:execute"SET NAMES UTF8"

-- 执行数据库操作
cur = conn:execute("select * from banner")

row = cur:fetch({},"a")

-- 文件对象的创建
file = io.open("role.txt","w+");



while row do
    var = ""
    -- 迭代输出
    for key, index in pairs(row) do
        var = string.format("%s %s:%s ", var, key, index)
        print(key, index)
    end
    var = string.format("%s\n", var)

    file:write(var)

    row = cur:fetch(row,"a")
end


file:close()  --关闭文件对象
conn:close()  --关闭数据库连接
env:close()   --关闭数据库环境